package com.example.augmentedrealityglasses

enum class ScreenName {
    HOME,
    FIND_DEVICE,
    ERROR_SCREEN,
    CONNECT_SCREEN,
    WEATHER_HOME_SCREEN,
    WEATHER_SEARCH_LOCATIONS,
    TRANSLATION_HOME_SCREEN,
    TRANSLATION_RESULT_SCREEN,
    TRANSLATION_LANGUAGE_SELECTION_SCREEN,
    SETTINGS
}